export const SHOW_LIST_EMAIL = 'SHOW_LIST_EMAIL'
export const SHOW_LIST_TRASH = 'SHOW_LIST_TRASH'
export const GET_ID = 'GET_ID'
export const GET_INDEX = 'GET_INDEX'
export const MOVE_TO_TRASH = 'MOVE_TO_TRASH'
export const MOVE_TO_INBOX = 'MOVE_TO_INBOX'
export const DELETE_PERMANENTLY = 'DELETE_PERMANENTLY'
export const SORT_EMAIL = 'SORT_EMAIL'
export const SEARCH_EMAIL = 'SEARCH_EMAIL'
export const SEND_EMAIL = 'SEND_EMAIL'

