export const SHOW_LIST_EMAIL = 'SHOW_LIST_EMAIL'
export const SHOW_LIST_TRASH = 'SHOW_LIST_TRASH'
export const SHOW_LIST_DRAFT = 'SHOW_LIST_DRAFT'
export const SHOW_LIST_SENT = 'SHOW_LIST_SENT'
export const MOVE_TO_TRASH = 'MOVE_TO_TRASH'
export const MOVE_TO_INBOX = 'MOVE_TO_INBOX'
export const DELETE_PERMANENTLY = 'DELETE_PERMANENTLY'
export const SORT_EMAIL = 'SORT_EMAIL'
export const SEARCH_EMAIL = 'SEARCH_EMAIL'
export const SEND_EMAIL = 'SEND_EMAIL'
export const RECEIVE_EMAIL = 'RECEIVE_EMAIL'
export const SAVE_TO_DRAFT = 'SAVE_TO_DRAFT'
export const DELETE_DRAFT = 'DELETE_DRAFT'
export const DELETE_SENT = 'DELETE_SENT'
export const READ_INBOX = 'READ_INBOX'
export const READ_TRASH = 'READ_TRASH'
export const READ_SENT = 'READ_SENT'
export const REPLY = 'REPLY'
export const FORWARD = 'FORWARD'
export const DRAFT = 'DRAFT'


